### PR TITLE
updated ckeditor constraint

### PR DESCRIPTION
**Pull request by schmunk42**

### CODE REVIEW

**Comment by schmunk42** [comment]
I had issues installing the version in composer.json
It should be a stable tag, are you currently referring to a branch?

Von meinem iPhone gesendet

**Comment by schmunk42** [comment]
I checked the version: https://semver.mwl.be/#?package=ckeditor%2Fckeditor&version=dev-full%2Fstable&minimum-stability=dev

You need stability `dev` for your project to "see" `dev-full/stable" - contents of 4.6 and the former look OK to me, please double check it.

**Comment by schmunk42** [comment]
That's the problem: https://github.com/ckeditor/ckeditor-releases/issues/41

**Comment by tonydspaniard** [comment]
@schmunk42 is this PR still relevant? Have you tried that if you make those changes the presets and all possible plugins still working? 

Thanks!

**Comment by schmunk42** [comment]
It is relevant, because currently this is broken, if you're not on `dev`.

As an example: https://github.com/dmstr/phd5-app/blob/a0a7b39a5cd97b669b32073c0af1c08229dd13ad/composer.phd5.json#L19
We have to use the constraint and require the package explicitly in our root `composer.json` - which defeats the purpose of dependency management.

Because of ckeditor/ckeditor-releases#41 - it seems like there's currently no 100% solution.
I'd recommend to switch on a working composer/release tag and add a section to the docs how to use all plugins.

**Comment by tonydspaniard** [comment]
> Because of ckeditor/ckeditor-releases#41 - it seems like there's currently no 100% solution.
I'd recommend to switch on a working composer/release tag and add a section to the docs how to use all plugins. 

Due to all these issues, thats why I considered in the past using assets folder within the library. CKEditor comes with far too many problems with their composer set.  But community swapped. I am not sure we could get a proper composer release version with it. Let's work on it.

**Comment by schmunk42** [comment]
> Due to all these issues, thats why I considered in the past using assets folder within the library.

It's merely an issue with `ckeditor`, bundling the assets with the PHP package is heading into the wrong direction, since you have to update it manually all the time.

What's about not using the composer package, but rather npm?

**Comment by tonydspaniard** [comment]
Thank you master blaster @schmunk42 ! Versioning fixed! :)

**Pull request closed without merging**
